# This config file for Travis CI utilizes https://github.com/davetcoleman/moveit_ci/ package.
sudo: required
dist: trusty
services:
  - docker
language: generic
compiler:
  - gcc
env:
  matrix:
    - ROS_DISTRO="kinetic"  ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE=moveit.rosinstall BEFORE_SCRIPT='./moveit_kinetic_cpp11/run_before.sh' TEST_BLACKLIST='octomap octovis dynamic_edt_3d fcl'

before_script:
  - git clone -q https://github.com/j-rivero/moveit_ci.git .moveit_ci

script:
  - source .moveit_ci/travis.sh
