# This config file for Travis CI utilizes https://github.com/davetcoleman/moveit_ci/ package.
sudo: required
dist: trusty
services:
  - docker
language: generic
compiler:
  - gcc
notifications:
  email:
    recipients:
      - dave@dav.ee
env:
  matrix:
    - ROS_DISTRO="kinetic"  ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu UPSTREAM_WORKSPACE=moveit.rosinstall BEFORE_SCRIPT='apt-get -qq remove libfcl0 libfcl-dev ros-kinetic-octomap && cd fcl && wget https://raw.githubusercontent.com/ros-gbp/fcl-release/debian/jade/fcl/package.xml && ../'
before_script:
  - git clone -q https://github.com/ros-planning/moveit_ci.git .moveit_ci
script:
  - source .moveit_ci/travis.sh
