# This config file for Travis CI utilizes https://github.com/davetcoleman/moveit_ci/ package.
sudo: required
dist: trusty
services:
  - docker
language: generic
compiler:
  - gcc
notifications:
  email:
    recipients:
      - dave@dav.ee
env:
  matrix:
    - ROS_DISTRO="kinetic"  ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE=moveit.rosinstall BEFORE_SCRIPT='./moveit_kinetic_cpp11/run_before.sh' TEST_BLACKLIST='octomap octovis dynamic_edt_3d fcl'
before_script:
  - git clone -q https://github.com/ros-planning/moveit_ci.git -b blacklist_tests .moveit_ci
script:
  - source .moveit_ci/travis.sh
