# This config file for Travis CI utilizes https://github.com/davetcoleman/moveit_ci/ package.
sudo: required
dist: trusty
services:
  - docker
language: generic
compiler:
  - gcc
notifications:
  email:
    recipients:
      - dave@dav.ee
env:
  matrix:
    - ROS_DISTRO="kinetic"  ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu UPSTREAM_WORKSPACE=moveit.rosinstall BEFORE_SCRIPT='./moveit_kinetic_cpp11/run_before.sh' TEST_BLACKLIST='octomap fcl'
before_script:
  - git clone -q https://github.com/ros-planning/moveit_ci.git .moveit_ci
  - git -C .moveit_ci am ../0001-Allow-blacklisting-packages-for-testing.patch
script:
  - source .moveit_ci/travis.sh
